services:
  pg_chainlink:
    image: "postgres"
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - /Users/ithihasreddy/Desktop/chainlink-rinkeby/data:/var/lib/postgressql/data/
  chainlink:
    image: "smartcontract/chainlink:1.3.0"
    ports:
      - 6688:6688
    env_file:
      - .env
    volumes:
      - /Users/ithihasreddy/Desktop/chainlink-rinkeby/chainlink-volume:/chainlink/
    depends_on:
      - pg_chainlink
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt